<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/*
  |--------------------------------------------------------------------------
  | Roles
  | 	the Role values are autogenerated values from database
  |--------------------------------------------------------------------------
 */
$config['rbac_roles'] = array(
    'view' => 1,
    'add' => 2,
    'edit' => 3,
    'reset' => 6,
    'admin' => 10,
    'hr_manager' => 22
);
/*
  |--------------------------------------------------------------------------
  | Controllers -- Task Group
  | 	the Task Group values are autogenerated values from database
  |--------------------------------------------------------------------------
 */
$config['rbac_groups'] = array(
    'Usermanagement' => 8,
    'Example' => 9,
    'Control_Panel' => 20,
    'Employee' => 21,
    'Reports' => 26,
    'AdminDashboard'=> 27,
);
/* End of file rbac_itschool.php */
/* Location: ./application/config/rbac_itschool.php */
